In [ ]:
#numpy:
#Numerical python
#It is a library used for working with Arrays.

In [ ]:
#Array: Array is a data structure that is used to store the element of same datatype in a organized way and faster access
#array is same as list (but list has collection of dissimilar data types).

In [ ]:
#Types:
#one and multi dimensional arrays

In [86]:
#! pip install <name_of_package>
#Here we want numpy so pip install Numpy
!pip install numpy

In [87]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
import numpy as np
print(np.__version__)

1.19.2


In [5]:
#creation of an array
#way 1:
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [6]:
#way 2:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [7]:
#diff between way 1 and way 2 bracket 
# passing a list in way1 and passing a tuple in way 2

In [8]:
import numpy as np

list1 = [1,2,3,4]
tup1 = (1,2,3,4)


In [9]:
np.array(tup1)

array([1, 2, 3, 4])

In [10]:
np.array(list1)

array([1, 2, 3, 4])

In [11]:
#Creation of array
#we need to give similar data 


import numpy as np

arr1 =np.array([10,100,1000,10000])
arr1

array([   10,   100,  1000, 10000])

In [12]:
arr2 = np.array(['s','t','u'])
arr2

array(['s', 't', 'u'], dtype='<U1')

In [13]:
arr3 = np.array(['a',2,'c'])
arr3

array(['a', '2', 'c'], dtype='<U1')

In [14]:
#every thing is converted into string. y string? because string can take number as well where as the number cannot take string
#hence all the numbers are stored as string

arr4 = np.array([1,2,3,4,'5'])
arr4

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [15]:
arr4[3]

'4'

In [16]:
arr4[3:]

array(['4', '5'], dtype='<U11')

In [17]:
#what if if we specify float.all will become float because float can take numbers but integer cant take float
arr5 = np.array([1,2,3,4,5.4])
print(arr5)
print(arr5[0::2])

[1.  2.  3.  4.  5.4]
[1.  3.  5.4]


In [18]:
type(arr5)

numpy.ndarray

In [19]:
import numpy as np

arr=np.array([1,2,3,4])
print(arr[0])
arr.shape

1


(4,)

In [20]:
#array can be one,two,multi dimensional

#one dimensional = [1,2,3]/

In [21]:
#creation of 2d Array
import numpy as np

arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [22]:
#Tpe:

type(arr_2d)

numpy.ndarray

In [23]:
#Shape:

arr_2d.shape

(2, 3)

In [24]:
#indexing

arr_2d[0,2]

3

In [25]:
arr_2d[1,2]

6

In [26]:
#Creation of 3d array
arr_3d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
type(arr_3d)

numpy.ndarray

In [28]:
arr_3d.shape

(3, 3)

In [29]:
arr_3d[0,2]

3

In [30]:
arr_3d[1,1]

5

In [31]:
arr_3d[2,2]

9

In [32]:
arr_3d[2,0:]

array([7, 8, 9])

In [33]:
arr_3d[0,-1:]

array([3])

In [34]:
#axis is nothing but row and column
#array in array is called n dimensional array


In [35]:
# in numpy we can create one and zero arrays directly just we need to specify no of rows and no of cloumns
import numpy as np
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
#reshaping of an array:Changing the shape of an array
#by applying reshaping of an array we can add or remove dimenions
# and can edit no of elements in each dimensions
#you should not have any remainder

arr0=np.array([10,20,30,40])
arr0

array([10, 20, 30, 40])

In [38]:
arr0.shape

(4,)

In [39]:
arr0_reshape=arr0.reshape(2,2)
arr0_reshape

array([[10, 20],
       [30, 40]])

In [40]:
arr0_reshape.shape

(2, 2)

In [41]:
arr5

array([1. , 2. , 3. , 4. , 5.4])

In [42]:
arr5_reshape=arr5.reshape(1,5)
arr5_reshape

array([[1. , 2. , 3. , 4. , 5.4]])

In [43]:
arr5_reshape=arr5.reshape(5,1)
arr5_reshape

array([[1. ],
       [2. ],
       [3. ],
       [4. ],
       [5.4]])

In [44]:
#iteraing array
#for loop

In [45]:
import numpy as np
arr6 = np.array([1,2,3,4,5,6])
arr6

array([1, 2, 3, 4, 5, 6])

In [46]:
for i in arr6:
    print(i)

1
2
3
4
5
6


In [47]:
#Joining array
import numpy as np
arr_a=np.array([1,2,3,4])
arr_b=np.array([5,6,7,8])
arr=np.concatenate((arr_a,arr_b))
print(arr)

[1 2 3 4 5 6 7 8]


In [48]:
#sorting

arr_10=np.array([3,5,6,9,7])
arr_10

array([3, 5, 6, 9, 7])

In [49]:
arr_10.sort()
arr_10

array([3, 5, 6, 7, 9])

In [50]:
import numpy as np
arr_11=np.array(['z','a','y','b'])
print(arr_11)

['z' 'a' 'y' 'b']


In [51]:
arr_11.sort()  #descending order
arr_11

array(['a', 'b', 'y', 'z'], dtype='<U1')

In [52]:
#Spliting opp to joining
#breaking of arrays
import numpy as np
arr_12=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr_12,3)
print(newarr)



[array([1, 2]), array([3, 4]), array([5, 6])]


In [53]:
#searching
arr_12

array([1, 2, 3, 4, 5, 6])

In [54]:
np.where(arr_12==4)

(array([3], dtype=int64),)

In [55]:
#filter: it is used to subset the data
filter=[True,False,True,False]


In [56]:
arr_11[filter]

array(['a', 'y'], dtype='<U1')

In [57]:
arr_11

array(['a', 'b', 'y', 'z'], dtype='<U1')

In [58]:
arr_11[arr_11=='y']

array(['y'], dtype='<U1')

In [65]:
#random integer
random.randint(100)

76

In [59]:
#random number in nupmy
from numpy import random
x=random.randint(10)
print(x)

8


In [68]:
x=random.randint(100,size=(100))
print(x)

[35 26 21 46 26 77 36 48 71 11 92  8 52 58 45 41 29 42 17 34 25 93 57 95
 85 35 31 20 50 22 66 34 34 74 37 46  3 87  0 96 32 42 75 64 74 14 30 68
 74 44 15 31 67 30 43 50 42 78 23 25 35 21 48 35 26 35 97 34 32 44 28 72
 77 61 62 75 15 32  6 85 42 12 88 44 28 38 60 19 62 55 97 99 56 46 20 19
 67 59 57 25]


In [69]:
random.rand()

0.3339019973698222

In [70]:
#diff between rand int and rand
#randint has integer values 
#rand will have float

In [72]:
#random.choice(for particular numbers)
from numpy import random
x=random.choice([2,4,6,8])
print(x)


6


In [74]:
x=random.choice([2,4,6,8],size=(2,2))
print(x)

[[8 2]
 [8 4]]


In [75]:
#Numpy operations
import numpy as np
x=np.array([1,2,3])
y=np.array([6,5,4])
z=x+y
print(z)

[7 7 7]


In [77]:
#matrix multiplication
import numpy as np
x=np.array([1,2,3])
y=np.array([6,5,4])
print(np.dot(x,y))


28


In [78]:
x=np.array([1,2,3])
y=np.array([6,5,4])
z=x-y
print(z)

[-5 -3 -1]
